import { TanStackProvider } from "@/components/templates/tanstack-providers";
import { ThemeProvider } from "@/components/templates/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head />
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <TanStackProvider>
            {children}
            <Toaster richColors />
          </TanStackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};
export default RootLayout;
