import { ThemeProvider } from "@/components/templates/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <head />
        <body className={inter.className}>{children}</body>
      </ThemeProvider> */}
      <head />
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};
export default RootLayout;
